### ISSUE TITLE
Clarify that ffmpeg and youtube-dl are necessary in REAMDE.md

### ISSUE THREAD

**Issue by ryonakano** [torikulhabib/mindi#19]
This app seems to require ffmpeg and youtube-dl as dependencies, and they are written in `debian/control`. However, they are not written in the README.md. If we build the app from code without them, the following error message is shown and video/audio files are not converted:

```
** (com.github.torikulhabib.mindi:11386): WARNING **: 11:54:08.410: Converter.vala:362: Failed to execute child process “ffmpeg” (No such file or directory)
```

I think we may want to claryfy that they are necessary in README.md.

**Comment by torikulhabib** [comment]
thanks
