### ISSUE TITLE
String size limit is inconvenient for translators

### ISSUE THREAD

**Issue by NathanBnm** [torikulhabib/mindi#28]
I figured out that some strings are truncated with the ellipsis symbol when they are to long. For some translations, in French for my example some labels doesn't fit.

And for the text under the progress bar, for example in French the bitrate isn't displaying because it's overflowing the window.

**Maybe you should increase a bit the limit**

**Comment by torikulhabib** [comment]
https://github.com/torikulhabib/mindi/commit/3ef741e88ba191d12e2e48b78112340a4443d724
