### ISSUE TITLE
Feature request: Remove video extension in audio name

### ISSUE THREAD

**Issue by btd1337** [torikulhabib/mindi#8]
.mp4

![captura de tela de 2018-11-19 00-50-32](https://user-images.githubusercontent.com/11943860/48683619-38c6b080-eb95-11e8-9806-48831038c1ad.png)

**Comment by torikulhabib** [comment]
Thanks.
fix this
https://github.com/torikulhabib/mindi/commit/d89a7553536dd5c803ca5d3fc4b099d197e58ae1
